# Generated by Django 5.2.6 on 2025-09-29 05:45

import django.db.models.deletion
import django.utils.timezone
import node_red.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('node_red', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JWTPublicKey',
            fields=[
                ('id', models.UUIDField(default=node_red.models.generate_uuid_public_key, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text="A descriptive name for the key (e.g., 'Payment Service Public Key').", max_length=100)),
                ('public_key', models.TextField(help_text='Paste the public key in PEM format here. The system will analyze it.')),
                ('algorithm', models.CharField(blank=True, choices=[('RS256', 'RS256 (Asymmetric, RSA-SHA256)'), ('ES256', 'ES256 (Asymmetric, ECDSA-SHA256)')], editable=False, help_text='The algorithm of the key, detected automatically.', max_length=10)),
                ('key_size', models.PositiveIntegerField(blank=True, editable=False, help_text='The key size (in bits), detected automatically.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True, help_text='You can deactivate a key instead of deleting it.')),
            ],
            options={
                'verbose_name': 'JWT Public Key',
                'verbose_name_plural': 'JWT Public Keys',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='element',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='element',
            name='details',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='element',
            name='device',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='node_red.device'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='device',
            name='id',
            field=models.UUIDField(default=node_red.models.generate_uuid_device, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='element',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='element',
            name='id',
            field=models.UUIDField(default=node_red.models.generate_uuid_element, editable=False, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Connections',
            fields=[
                ('id', models.UUIDField(default=node_red.models.generate_uuid_connection, editable=False, primary_key=True, serialize=False)),
                ('details', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connections', to='node_red.device')),
            ],
        ),
        migrations.AddField(
            model_name='device',
            name='public_key',
            field=models.ForeignKey(blank=True, help_text='The unique public key that identifies this device.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='node_red.jwtpublickey'),
        ),
    ]
