# Generated by Django 5.2.6 on 2025-10-01 05:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('node_red', '0003_elementdetailsstyle_style_stylefiles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stylefiles',
            name='style',
        ),
        migrations.AddField(
            model_name='elementdetailsstyle',
            name='element',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='style_details', to='node_red.element'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='elementdetailsstyle',
            name='name',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Style',
        ),
        migrations.DeleteModel(
            name='StyleFiles',
        ),
    ]
