# Generated by Django 5.2.6 on 2025-10-03 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('node_red', '0004_remove_stylefiles_style_elementdetailsstyle_element_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='element',
            name='element_id',
        ),
        migrations.AlterField(
            model_name='device',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
