# Generated by Django 5.1.5 on 2025-09-26 01:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('node_red', '0010_element_created_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JWTSigningKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="A descriptive name for the key (e.g., 'Payment Service Key').", max_length=100)),
                ('algorithm', models.CharField(choices=[('RS256', 'RS256 (Asymmetric, RSA-SHA256)'), ('ES256', 'ES256 (Asymmetric, ECDSA-SHA256)')], help_text='The algorithm used to generate the key pair.', max_length=10)),
                ('key_size', models.PositiveIntegerField(default=2048, help_text='For RSA (in bits): 2048 or 4096. This is ignored for ES256.')),
                ('private_key', models.TextField(blank=True, help_text='The private key in PEM format. Generated automatically. Never share this.')),
                ('public_key', models.TextField(blank=True, help_text='The public key in PEM format. Generated automatically. This can be shared safely.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True, help_text='You can deactivate a key instead of deleting it.')),
                ('user', models.ForeignKey(help_text='The user who owns this key.', on_delete=django.db.models.deletion.CASCADE, related_name='jwt_keys', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'JWT Signing Key',
                'verbose_name_plural': 'JWT Signing Keys',
                'ordering': ['-created_at'],
            },
        ),
    ]
